name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'latest'
          
      - name: Install dependencies
        run: npm install
        
      - name: Build
        run: npm run build
        
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Add host key
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy with rollback
        run: |
          # 创建时间戳目录
          TIMESTAMP=$(date +%Y%m%d_%H%M%S)
          DEPLOY_DIR="${{ secrets.DEPLOY_PATH }}/releases/${TIMESTAMP}"
          CURRENT_LINK="${{ secrets.DEPLOY_PATH }}/current"
          
          # 创建发布目录
          ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} "mkdir -p ${DEPLOY_DIR}"
          
          # 复制构建文件到服务器
          scp -r _site/* ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }}:${DEPLOY_DIR}
          
          # 部署新版本（使用原子操作）
          ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} "
            ln -sfn ${DEPLOY_DIR} ${CURRENT_LINK}.tmp && \
            mv -Tf ${CURRENT_LINK}.tmp ${CURRENT_LINK} && \
            echo 'Deployment successful!' || \
            (echo 'Deployment failed, rolling back...' && \
            rm -rf ${DEPLOY_DIR} && \
            exit 1)
          "
          
          # 保留最近的5个部署版本，删除旧版本
          ssh ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_HOST }} "
            cd ${{ secrets.DEPLOY_PATH }}/releases && \
            ls -t | tail -n +6 | xargs -r rm -rf
          "
